### ISSUE TITLE
[IDEA] serverless.yml for SNS Topic & Subscription Resource creation

### ISSUE THREAD

**Issue by Chris1904** [meemalabs/laravel-media-recognition#12]
Hi everyone,

I really enjoy working with the Serverless Framework, as it allows you to easily create & manage your AWS Resources via code.

We could create the serverless.yml file, so the SNS Topic and Subscription could be created via `sls deploy`. Would simplify parts of the readme.

Any thoughts?

**Comment by chrisbbreuer** [comment]
https://github.com/meemalabs/laravel-media-recognition/discussions/17
