### ISSUE TITLE
[IDEA] Support Azure Vision Service Cognitive

### ISSUE THREAD

**Issue by Oxicode** [meemalabs/laravel-media-recognition#16]
### Prerequisites
Account Azure

### Versions

* PHP version: 7.4
* Laravel version: > 8
* Package version: 

### Additional Information

Any additional information, configuration or data that might be needed to understand the proposal.

**Comment by Chris1904** [comment]
Hi Oxicode! 

This surely is a great addition to the package and it's definitely on our backlog to support it. We don't have a timeline for this internally yet, but it will eventually be explored if the support has not been added by that time.

Thanks for the suggestion!

Chris

**Comment by chrisbbreuer** [comment]
https://github.com/meemalabs/laravel-media-recognition/discussions/19
